name: RankQuests
author: Yukun
main: me.Yukun.RankQuests.Main
version: 1.0.25a
softdepend: [Factions, WorldGuard, LegacyFactions]
description: >
             A plugin to make players complete a timed quest before they receive a rank.
commands:
  rankquest:
    description: Main command for rank quest related actions.
    aliases: [rankquest, rq, quest]